services:
  sigmentum:
    image: registry.digitalocean.com/tfwo-container-registry/sigmentum:latest
    container_name: sigmentum
    restart: always
    environment:
      - Sigmentum__StockApiKey=${Sigmentum__StockApiKey}
      - Sigmentum__EnableStockScanning=${Sigmentum__EnableStockScanning}
      - ConnectionStrings__DBConnection=${ConnectionStrings__DBConnection}
    ports:
      - "5000:8080"